# configuration
dist: trusty
sudo: required
language: java
cache:
  directories:
  - $HOME/.m2
  - node_modules

# build matrix
jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-setuptools 
  - sudo easy_install3 pip
  - export LC_ALL=C
  - sudo pip3 install -U nltk
  - nvm install node
  - nvm use node
   
# run steps
install:
  - cd core 
  - cd new-gui
  - npm install
  - cd ..

script:
  - mvn test --batch-mode
  - cd new-gui
  - ng test
  
