# configuration
dist: trusty
sudo: required
language: java
cache:
  directories:
  - $HOME/.m2

# build matrix
jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-setuptools 
  - sudo easy_install3 pip
  - export LC_ALL=C
  - sudo pip3 install -U nltk
  - nvm install node
  - nvm use node
  - npm install -g @angular/cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
   
# run steps
install:
  - cd core 
  - cd new-gui
  - npm install
  - cd ..

script:
  - mvn test --batch-mode
  - cd new-gui
  - ng build --aot
  - ng test --browsers ChromeHeadless --watch=false
  
