# configuration
language: java
cache:
    - apt
    - $HOME/.m2

# build matrix
jdk:
    - oraclejdk8

before_install:
  - uname -a
  -	sudo apt-get update && sudo apt-get install python3-pip
#  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrappe
  - python3 -V
  - pip3 -V
   
# run steps
install:

script:
    - cd textdb 
    - mvn test
