# configuration
language: java
cache:
    - apt
    - $HOME/.m2

# build matrix
jdk:
    - oraclejdk8

before_install:
  - sudo apt-get install python3-setuptools 
  - sudo easy_install3 pip
  - sudo pip install -U nltk
  - sudo pip install -U numpy
#  - sudo apt-get -y install python3-pip python-dev
#  - sudo apt-get -y install python3-pip python-dev
#  - sudo pip3 install -U setuptools
#  - sudo pip3 install -U virtualenvwrappe
  - python3 -V
   
# run steps
install:

script:
    - cd textdb 
    - mvn test
