name: build

on:
  push:
    branches:
      - 'ci-enable/**'
      - 'master'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  gui:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 18
        architecture:
          - x64
    steps:
      - name: Checkout Texera
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
      - uses: actions/cache@v2
        with:
          path: |
            core/gui/node_modules
            core/gui/multi-target/node_modules
          key: ${{ runner.os }}-yarn-cache-v6-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-v6-
      - name: Install dependency
        run: yarn --cwd core/gui install --frozen-lockfile --progress=false --network-timeout=100000
      - name: Lint with Prettier & ESLint
        run: yarn --cwd core/gui format:ci
      - name: Run frontend unit tests
        run: yarn --cwd core/gui run test:ci
      - name: Prod build
        run: yarn --cwd core/gui run build:ci

  amber:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        java-version: [ 8, 11 ]
    runs-on: ${{ matrix.os }}
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: Prepare ENV
        run: sudo apt-get install libncurses5
      - name: Checkout Texera
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - uses: coursier/cache-action@v6
        with:
          extraSbtFiles: '["core/amber/*.sbt", "core/amber/project/**.{scala,sbt}", "core/amber/project/build.properties" ]'
      - name: Lint with scalafix & scalafmt
        run: cd core/amber && sbt "scalafixAll --check" && sbt scalafmtCheckAll
      - name: Compile with sbt
        run: cd core/amber && sbt clean package
      - name: Run backend tests
        run: cd core/amber && sbt -v -J-Xmx2G test

  python_udf:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]

    steps:
      - name: Checkout Texera
        uses: actions/checkout@v2
      - name: Set up R for R-UDF
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'
      - name: Install R dependencies for R-UDF
        run: |
          Rscript -e 'install.packages("dplyr", repos = "http://cran.rstudio.com/")'
          Rscript -e 'install.packages("arrow", version = "14.0.0.1", repos = "http://cran.rstudio.com/")'
          Rscript -e 'install.packages("reticulate", version = "1.36.1", repos = "http://cran.rstudio.com/")'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f core/amber/requirements.txt ]; then pip install -r core/amber/requirements.txt; fi
          if [ -f core/amber/operator-requirements.txt ]; then pip install -r core/amber/operator-requirements.txt; fi
      - name: Lint with flake8 and black
        run: |
          cd core/amber/src/main/python && flake8 && black . --check
      - name: Test with pytest
        run: |
          cd core/amber/src/main/python && pytest -sv
